export { default as playTemplate0 } from "./play-template-0.vue"
export { default as playTemplate1 } from "./play-template-1.vue"
export { default as playTemplate2 } from "./play-template-2.vue"
export { default as playTemplate3 } from "./play-template-3.vue"
export { default as playTemplate4 } from "./play-template-4.vue"
export { default as playTemplate5 } from "./play-template-5.vue"
export { default as playTemplate6 } from "./play-template-6.vue"