<!--
 * @Author: rise
 * @Date: 2023-10-22 17:03:22
 * @LastEditors: rise
 * @LastEditTime: 2023-10-27 18:46:56
 * @Description:  
-->
<template>
    <div class="swiper-wap">
        <div class="swiper-content swiper-left">
            <SwiperNav :slideList="slideImgList" @swiperChange="swiperChange"/>
        </div>
        <div class="swiper-content swiper-right">
            <SwiperNav :slideList="slidEeventList" @swiperChange="swiperChange"/>
        </div>
    </div>
</template>
<script setup>
import SwiperNav from "./swiper-nav.vue";
import { ref, onMounted } from "vue";
import { api_home } from "src/api/index.js";
import { get_server_file_path } from "src/output/index.js";
import { useRouter } from "vue-router";
import store from "src/store-redux/index.js";
const store_state = store.getState();
const router = useRouter();
/**
 * 图片轮播
 */
// const slideImgList = [
//   {
//     img:"https://cdn.quasar.dev/img/mountains.jpg",
//     toUrl:""
//   },
//   {
//     img:"https://cdn.quasar.dev/img/parallax1.jpg",
//     toUrl:""
//   },
//   {
//     img:"https://cdn.quasar.dev/img/parallax2.jpg",
//     toUrl:""
//   },
//   {
//     img:"https://cdn.quasar.dev/img/quasar.jpg",
//     toUrl:""
//   },
// ];
/**
 * 赛事轮播
 */
// const slidEeventList = [
//     {
//         isGame:true,//是否赛事
//         anchorName:"名称",//主播名称
//         anchorAvatar:"https://cdn.quasar.dev/img/quasar.jpg",//主播头像
//         gameName:"欧洲足球联赛",//比赛名称
//         gameParticipants:[//参赛方信息
//             {
//                 name:"美国",
//                 avatar:"https://cdn.quasar.dev/img/parallax2.jpg"//头像
//             },
//             {
//                 name:"日本",
//                 avatar:"https://cdn.quasar.dev/img/parallax1.jpg"
//             }
//         ]
//     },
//     {
//         isGame:true,
//         anchorName:"名称1",//主播名称
//         anchorAvatar:"https://cdn.quasar.dev/img/quasar.jpg",//主播头像
//         gameName:"欧洲足球联赛",//比赛名称
//         gameParticipants:[//参赛方信息
//             {
//                 name:"美国",
//                 avatar:"https://cdn.quasar.dev/img/parallax2.jpg"//头像
//             },
//             {
//                 name:"日本",
//                 avatar:"https://cdn.quasar.dev/img/parallax1.jpg"
//             }
//         ]
//     }
// ]
const slideImgList = ref([]);//图片轮播
const slidEeventList = ref([]);//赛事轮播
const get_banner_obj = ref(store_state.get_banner_obj);
/**
 * 轮播图点击事件
 * @param { Object } item 
 */
const swiperChange = (item,type) => {
    if(!type)return window.open(item.hostUrl);//图片跳转 逻辑暂无
    //赛事跳转 路由==改
    return router.push({ name: "category", params: { mid: item.mid, csid: item.csid } });
}
/**
 * 图片轮播
 */
const getSwiperImgList = () =>{
    slideImgList.value = get_banner_obj.value?.type1?.map((item)=>{
        item.imgUrl = get_server_file_path(item.imgUrl);
        item.toUrl = get_server_file_path(item.imgUrl);
        return item;
    })
};

/**
 * 足球赛事轮播
 */
const getSwiperList = async () =>{
    // const res = await api_home.hot_ulike_recommendation({ isHot: 101 });
    const res = {
        "code":"200",
        "data":[
            {
                "mcid":"周六016",
                "tnjc":"西甲",
                "hpsBold":[],
                "csna":"足球",
                "tid":"320",
                "mst":"0",
                "srid":"10246040",
                "mcg":4,
                "cosCorner":false,
                "atf":"1",
                "cosPunish":false,
                "cosOutright":false,
                "mdsc":null,
                "mc":127,
                "hpsOvertime":[],
                "mf":false,
                "mgt":"1698502500000",
                "maid":"3821",
                "mct":0,
                "tlev":1,
                "mhlut":"",
                "mo":0,
                "ctt":0,
                "mp":1,
                "csid":"1",
                "ms":0,
                "cmec":null,
                "cos5Minutes":true,
                "mle":0,
                "lvs":-1,
                "sort":100,
                "malu":[
                    "group1/M00/00/25/CgURtV7elMmAK8qxAAAe6ue9kCk578.png"
                ],
                "hps15Minutes":[
                    {
                        "hids":0,
                        "hl":[
                            {
                                "hid":"142578543340475810",
                                "hs":1,
                                "hv":null,
                                "hmt":1,
                                "hn":null,
                                "ad3":"15",
                                "ad5":"10100000",
                                "ol":[{
                                    "oid":"141133905017410456",
                                    "os":1,
                                    "otd":610,
                                    "ot":"1",
                                    "ov":500000,
                                    "onb":"主胜",
                                    "on":"巴塞罗那",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":"T1"
                                },{
                                    "oid":"143393568371359709",
                                    "os":1,
                                    "otd":612,
                                    "ot":"2",
                                    "ov":740000,
                                    "onb":"客胜",
                                    "on":"皇家马德里",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":"T2"
                                },{
                                    "oid":"141011346009771050",
                                    "os":1,
                                    "otd":611,
                                    "ot":"X",
                                    "ov":125000,
                                    "onb":"平局",
                                    "on":"平局",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":""
                                }]
                            }
                        ],
                        "hpn":"15分钟进球(开场-14:59)-独赢",
                        "mid":"2804729",
                        "hmm":0,
                        "hshow":"Yes",
                        "hpnb":"15分钟进球(开场-14:59)-独赢",
                        "hSpecial":"1",
                        "hpt":1,
                        "hsw":"1,4,5",
                        "hpid":"32",
                        "hpon":123,
                        "mct":"76"
                    },
                    {
                        "hids":0,
                        "hl":[
                            {
                                "hid":"140101424636043555",
                                "hs":1,
                                "hv":null,
                                "hmt":1,
                                "hn":null,
                                "ad3":"30",
                                "ad5":"10100000",
                                "ol":[{
                                    "oid":"141325063064265005",
                                    "os":1,
                                    "otd":610,
                                    "ot":"1",
                                    "ov":500000,
                                    "onb":"主胜",
                                    "on":"巴塞罗那",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":"T1"
                                },{
                                    "oid":"147841042411239170",
                                    "os":1,
                                    "otd":612,
                                    "ot":"2",
                                    "ov":740000,
                                    "onb":"客胜",
                                    "on":"皇家马德里",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":"T2"
                                },{
                                    "oid":"143790737767061145",
                                    "os":1,
                                    "otd":611,
                                    "ot":"X",
                                    "ov":125000,
                                    "onb":"平局",
                                    "on":"平局",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":""
                                }]
                            }
                        ],
                        "hpn":"15分钟进球(15:00-29:59)-独赢",
                        "mid":"2804729",
                        "hmm":0,
                        "hshow":"Yes",
                        "hpnb":"15分钟进球(15:00-29:59)-独赢",
                        "hSpecial":"2",
                        "hpt":1,
                        "hsw":"1,4,5",
                        "hpid":"32",
                        "hpon":123,
                        "mct":"76"
                    },
                    {
                        "hids":0,
                        "hl":[
                            {
                                "hid":"149950114516601897",
                                "hs":0,
                                "hv":"0",
                                "hmt":1,
                                "hn":null,
                                "ad3":"0",
                                "ad5":"1,15",
                                "ol":[{
                                    "oid":"144053330611683915",
                                    "os":1,
                                    "otd":613,
                                    "ot":"1",
                                    "ov":155000,
                                    "onb":"0",
                                    "on":"0",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":"T1"
                                },{
                                    "oid":"144645142231347257",
                                    "os":1,
                                    "otd":614,
                                    "ot":"2",
                                    "ov":233000,
                                    "onb":"0",
                                    "on":"0",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":"T2"
                                }]
                            }
                        ],
                        "hpn":"15分钟进球(开场-14:59)-让球",
                        "mid":"2804729",
                        "hmm":1,
                        "hshow":"Yes",
                        "hpnb":"15分钟进球(开场-14:59)-让球",
                        "hSpecial":"1",
                        "hpt":2,
                        "hsw":"1,2,3,4,5,6",
                        "hpid":"33",
                        "hpon":124,
                        "mct":"0.0"
                    },
                    {
                        "hids":0,
                        "hl":[
                            {
                                "hid":"141369537416000917",
                                "hs":0,
                                "hv":"0",
                                "hmt":1,
                                "hn":null,
                                "ad3":"0",
                                "ad5":"16,30",
                                "ol":[{
                                    "oid":"143757602162505248",
                                    "os":1,
                                    "otd":613,
                                    "ot":"1",
                                    "ov":155000,
                                    "onb":"0",
                                    "on":"0",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":"T1"
                                },{
                                    "oid":"143381035421753603",
                                    "os":1,
                                    "otd":614,
                                    "ot":"2",
                                    "ov":233000,
                                    "onb":"0",
                                    "on":"0",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":"T2"
                                }]
                            }
                        ],
                        "hpn":"15分钟进球(15:00-29:59)-让球",
                        "mid":"2804729",
                        "hmm":1,
                        "hshow":"Yes",
                        "hpnb":"15分钟进球(15:00-29:59)-让球",
                        "hSpecial":"2",
                        "hpt":2,
                        "hsw":"1,2,3,4,5,6",
                        "hpid":"33",
                        "hpon":124,
                        "mct":"0.0"
                    },
                    {
                        "hids":1,
                        "hl":[
                            {
                                "hid":"147605587127098434",
                                "hs":0,
                                "hv":"0.5",
                                "hmt":1,
                                "hn":null,
                                "ad3":"15",
                                "ad5":"",
                                "ol":[{
                                    "oid":"145701570098481490",
                                    "os":1,
                                    "otd":615,
                                    "ot":"Over",
                                    "ov":296000,
                                    "onb":"0.5",
                                    "on":"大 0.5",
                                    "onbl":"大 ",
                                    "cds":"AO",
                                    "ots":"T1"
                                },{
                                    "oid":"149162350112340801",
                                    "os":1,
                                    "otd":616,
                                    "ot":"Under",
                                    "ov":131000,
                                    "onb":"0.5",
                                    "on":"小 0.5",
                                    "onbl":"小 ",
                                    "cds":"AO",
                                    "ots":"T2"
                                }]
                            }
                        ],
                        "hpn":"15分钟进球(开场-14:59)-大小",
                        "mid":"2804729",
                        "hmm":1,
                        "hshow":"Yes",
                        "hpnb":"15分钟进球(开场-14:59)-大小",
                        "hSpecial":"1",
                        "hpt":5,
                        "hsw":"1,2,3,4,5,6",
                        "hpid":"34",
                        "hpon":126,
                        "mct":"76"
                    },
                    {
                        "hids":1,
                        "hl":[
                            {
                                "hid":"142574420205465535",
                                "hs":0,
                                "hv":"0.5",
                                "hmt":1,
                                "hn":null,
                                "ad3":"30",
                                "ad5":"",
                                "ol":[{
                                    "oid":"146232411250679350",
                                    "os":1,
                                    "otd":615,
                                    "ot":"Over",
                                    "ov":296000,
                                    "onb":"0.5",
                                    "on":"大 0.5",
                                    "onbl":"大 ",
                                    "cds":"AO",
                                    "ots":"T1"
                                },{
                                    "oid":"146025033380094162",
                                    "os":1,
                                    "otd":616,
                                    "ot":"Under",
                                    "ov":131000,
                                    "onb":"0.5",
                                    "on":"小 0.5",
                                    "onbl":"小 ",
                                    "cds":"AO",
                                    "ots":"T2"
                                }]
                            }
                        ],
                        "hpn":"15分钟进球(15:00-29:59)-大小",
                        "mid":"2804729",
                        "hmm":1,
                        "hshow":"Yes",
                        "hpnb":"15分钟进球(15:00-29:59)-大小",
                        "hSpecial":"2",
                        "hpt":5,
                        "hsw":"1,2,3,4,5,6",
                        "hpid":"34",
                        "hpon":126,
                        "mct":"76"
                    }
                ],
                "lurl":"group1/M00/19/99/CgURtWSyM0qAGqpZAAADLH17h_k076.png",
                "mprmc":"PA",
                "cosOvertime":false,
                "mhn":"巴塞罗那",
                "betAmount":"7.20",
                "cds":"BG",
                "frmhn":[
                    "B"
                ],
                "compose":true,
                "operationTournamentSort":133,
                "cos15Minutes":true,
                "mhs":0,
                "mlet":"45:00",
                "hps5Minutes":[
                    {
                        "mid":"2804729",
                        "chpid":"361",
                        "hpid":"361",
                        "hpon":225,
                        "hshow":"No",
                        "hpn":"5分钟时段进球",
                        "hpnb":"5分钟时段进球",
                        "hpt":3,
                        "hsw":"1,4,5",
                        "hmm":0,
                        "hids":0,
                        "hl":[{
                            "hid":"143118685803930133",
                            "hs":0,
                            "hv":null,
                            "hmt":1,
                            "hn":null,
                            "title":[
                                {
                                    "osn":"00:00-04:59",
                                    "otd":1154
                                },
                                {
                                    "osn":"05:00-09:59",
                                    "otd":1155
                                },
                                {
                                    "osn":"10:00-14:59",
                                    "otd":1156
                                },
                                {
                                    "osn":"15:00-19:59",
                                    "otd":1157
                                },
                                {
                                    "osn":"20:00-24:59",
                                    "otd":1158
                                },
                                {
                                    "osn":"25:00-29:59",
                                    "otd":1159
                                },
                                {
                                    "osn":"30:00-34:59",
                                    "otd":1160
                                },
                                {
                                    "osn":"35:00-39:59",
                                    "otd":1161
                                },
                                {
                                    "osn":"40:00-45:00",
                                    "otd":1162
                                },
                                {
                                    "osn":"下半场-49:59",
                                    "otd":1163
                                },
                                {
                                    "osn":"50:00-54:59",
                                    "otd":1164
                                },
                                {
                                    "osn":"55:00-59:59",
                                    "otd":1165
                                },
                                {
                                    "osn":"60:00-64:59",
                                    "otd":1166
                                },
                                {
                                    "osn":"65:00-69:59",
                                    "otd":1167
                                },
                                {
                                    "osn":"70:00-74:59",
                                    "otd":1168
                                },
                                {
                                    "osn":"75:00-79:59",
                                    "otd":1169
                                },
                                {
                                    "osn":"80:00-84:59",
                                    "otd":1170
                                },
                                {
                                    "osn":"85:00-90:00",
                                    "otd":1171
                                },
                                {
                                    "osn":"无进球(0-0)",
                                    "otd":1172
                                },
                                {
                                    "osn":"绝杀球(含上/下半场补时)",
                                    "otd":1173
                                }
                            ],
                            "ol":[{
                                "oid":"145420801411333443",
                                "os":1,
                                "otd":1154,
                                "ot":"1-5",
                                "ov":1000000,
                                "on":"00:00-04:59",
                                "onb":"00:00-04:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"144154427346705920",
                                "os":1,
                                "otd":1155,
                                "ot":"6-10",
                                "ov":780000,
                                "on":"05:00-09:59",
                                "onb":"05:00-09:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"145294878315275636",
                                "os":1,
                                "otd":1156,
                                "ot":"11-15",
                                "ov":780000,
                                "on":"10:00-14:59",
                                "onb":"10:00-14:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"144124200160102254",
                                "os":1,
                                "otd":1157,
                                "ot":"16-20",
                                "ov":850000,
                                "on":"15:00-19:59",
                                "onb":"15:00-19:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"140154350186462528",
                                "os":1,
                                "otd":1158,
                                "ot":"21-25",
                                "ov":850000,
                                "on":"20:00-24:59",
                                "onb":"20:00-24:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"144643212953224513",
                                "os":1,
                                "otd":1159,
                                "ot":"26-30",
                                "ov":850000,
                                "on":"25:00-29:59",
                                "onb":"25:00-29:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"143779693565098155",
                                "os":1,
                                "otd":1160,
                                "ot":"31-35",
                                "ov":900000,
                                "on":"30:00-34:59",
                                "onb":"30:00-34:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"146851401169905979",
                                "os":1,
                                "otd":1161,
                                "ot":"36-40",
                                "ov":900000,
                                "on":"35:00-39:59",
                                "onb":"35:00-39:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"141236460653048427",
                                "os":1,
                                "otd":1162,
                                "ot":"41-45",
                                "ov":900000,
                                "on":"40:00-45:00",
                                "onb":"40:00-45:00",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"147493128509534549",
                                "os":1,
                                "otd":1163,
                                "ot":"46-50",
                                "ov":880000,
                                "on":"下半场-49:59",
                                "onb":"下半场-49:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"147913240109112017",
                                "os":1,
                                "otd":1164,
                                "ot":"51-55",
                                "ov":740000,
                                "on":"50:00-54:59",
                                "onb":"50:00-54:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"141248100089002489",
                                "os":1,
                                "otd":1165,
                                "ot":"56-60",
                                "ov":740000,
                                "on":"55:00-59:59",
                                "onb":"55:00-59:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"143353767430325705",
                                "os":1,
                                "otd":1166,
                                "ot":"61-65",
                                "ov":670000,
                                "on":"60:00-64:59",
                                "onb":"60:00-64:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"146333830244472903",
                                "os":1,
                                "otd":1167,
                                "ot":"66-70",
                                "ov":670000,
                                "on":"65:00-69:59",
                                "onb":"65:00-69:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"140332264561487635",
                                "os":1,
                                "otd":1168,
                                "ot":"71-75",
                                "ov":670000,
                                "on":"70:00-74:59",
                                "onb":"70:00-74:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"143730581333817682",
                                "os":1,
                                "otd":1169,
                                "ot":"76-80",
                                "ov":660000,
                                "on":"75:00-79:59",
                                "onb":"75:00-79:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"140504729703244340",
                                "os":1,
                                "otd":1170,
                                "ot":"81-85",
                                "ov":660000,
                                "on":"80:00-84:59",
                                "onb":"80:00-84:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"140455143121923174",
                                "os":1,
                                "otd":1171,
                                "ot":"86-90",
                                "ov":660000,
                                "on":"85:00-90:00",
                                "onb":"85:00-90:00",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"146264626208629894",
                                "os":1,
                                "otd":1172,
                                "ot":"NoGoal",
                                "ov":850000,
                                "on":"无进球(0-0)",
                                "onb":"无进球(0-0)",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"140301001965094364",
                                "os":1,
                                "otd":1173,
                                "ot":"ClutchGoal",
                                "ov":600000,
                                "on":"绝杀球(含上/下半场补时)",
                                "onb":"绝杀球(含上/下半场补时)",
                                "cds":"AO",
                                "ots":""
                            }]
                        }]
                    },
                    {
                        "mid":"2768850",
                        "chpid":"362",
                        "hpid":"362",
                        "hpon":226,
                        "hshow":"No",
                        "hpn":"第 {!goalnr} 个进球时分(5min)",
                        "hpnb":"第 {!goalnr} 个进球时分(5min)",
                        "hpt":3,
                        "hsw":"1,4,5",
                        "hmm":0,
                        "hids":0,
                        "hl":[{}]
                    }
                ],
                "cosPenalty":false,
                "hpsCorner":[],
                "mhid":"3783",
                "hpsPunish":[],
                "mrmc":"",
                "mid":"2804729",
                "mess":1,
                "cosBold":true,
                "lss":null,
                "mmp":"0",
                "mststi":"0",
                "mms":1,
                "mbmty":1,
                "regionIdSort":1,
                "mhlu":[
                    "group1/M00/00/25/CgURtl7kE6KAA6DyAAAWUfTSmUE157.png"
                ],
                "seid":"112094",
                "mstst":"0",
                "malut":"",
                "man":"皇家马德里",
                "frman":[
                    "H"
                ],
                "mat":"",
                "mng":0,
                "mststr":"0",
                "hps":[
                    {
                        "mid":"2804729",
                        "chpid":"4",
                        "hpid":"4",
                        "hpon":4,
                        "hshow":"Yes",
                        "hpn":"全场让球",
                        "hpnb":"全场让球",
                        "hpt":2,
                        "hsw":"1,2,3,4,5,6",
                        "hmm":1,
                        "hids":1,
                        "hl":[{
                            "hid":"141382573440835434",
                            "hs":0,
                            "hv":"-0.5",
                            "hmt":1,
                            "hn":1,
                            "ol":[{
                                "oid":"142828755896399323",
                                "os":1,
                                "otd":3,
                                "ot":"1",
                                "ov":200000,
                                "on":"-0.5",
                                "onb":"-0.5",
                                "cds":"AO",
                                "ots":"T1"
                            },{
                                "oid":"143072444550306524",
                                "os":1,
                                "otd":4,
                                "ot":"2",
                                "ov":182000,
                                "on":"+0.5",
                                "onb":"+0.5",
                                "cds":"AO",
                                "ots":"T2"
                            }]
                        }]
                    }
                ],
                "hpsCompose":[],
                "mvs":1,
                "hpsPenalty":[],
                "mststs":0,
                "mearlys":0,
                "tf":false,
                "th":1,
                "cosPromotion":false,
                "mfo":null,
                "mft":0,
                "tn":"西班牙甲级联赛",
                "msc":[],
                "hpsPromotion":[],
                "hpsOutright":[]
            },
            {
                "mcid":"",
                "tnjc":"英联杯",
                "hpsBold":[],
                "csna":"足球",
                "tid":"2137",
                "mst":"0",
                "srid":"10543398",
                "mcg":4,
                "cosCorner":false,
                "atf":"1",
                "cosPunish":false,
                "cosOutright":false,
                "mdsc":null,
                "mc":0,
                "hpsOvertime":[],
                "mf":false,
                "mgt":"1698867000000",
                "maid":"7998",
                "mct":0,
                "tlev":4,
                "mhlut":"",
                "mo":0,
                "ctt":0,
                "mp":1,
                "csid":"1",
                "ms":0,
                "cmec":null,
                "cos5Minutes":true,
                "mle":0,
                "lvs":-1,
                "sort":100,
                "malu":[
                    "group1/M00/00/27/CgURtl7pE-aAakmXAAAcQRvHZqY878.png"
                ],
                "hps15Minutes":[
                    {
                        "hids":0,
                        "hl":[
                            {
                                "hid":"141614190570042095",
                                "hs":2,
                                "hv":null,
                                "hmt":1,
                                "hn":null,
                                "ad3":"15",
                                "ad5":"10100000",
                                "ol":[{
                                    "oid":"140331415721455550",
                                    "os":1,
                                    "otd":610,
                                    "ot":"1",
                                    "ov":620000,
                                    "onb":"主胜",
                                    "on":"西汉姆联",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":"T1"
                                },{
                                    "oid":"148382723775914491",
                                    "os":1,
                                    "otd":612,
                                    "ot":"2",
                                    "ov":580000,
                                    "onb":"客胜",
                                    "on":"阿森纳",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":"T2"
                                },{
                                    "oid":"142490222942942258",
                                    "os":1,
                                    "otd":611,
                                    "ot":"X",
                                    "ov":126000,
                                    "onb":"平局",
                                    "on":"平局",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":""
                                }]
                            }
                        ],
                        "hpn":"15分钟进球(开场-14:59)-独赢",
                        "mid":"2782347",
                        "hmm":0,
                        "hshow":"Yes",
                        "hpnb":"15分钟进球(开场-14:59)-独赢",
                        "hSpecial":"1",
                        "hpt":1,
                        "hsw":"1,4,5",
                        "hpid":"32",
                        "hpon":123,
                        "mct":"76"
                    },
                    {
                        "hids":0,
                        "hl":[
                            {
                                "hid":"147003814130920323",
                                "hs":2,
                                "hv":null,
                                "hmt":1,
                                "hn":null,
                                "ad3":"30",
                                "ad5":"10100000",
                                "ol":[{
                                    "oid":"149046712854071507",
                                    "os":1,
                                    "otd":610,
                                    "ot":"1",
                                    "ov":580000,
                                    "onb":"主胜",
                                    "on":"西汉姆联",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":"T1"
                                },{
                                    "oid":"144347023568852317",
                                    "os":1,
                                    "otd":612,
                                    "ot":"2",
                                    "ov":550000,
                                    "onb":"客胜",
                                    "on":"阿森纳",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":"T2"
                                },{
                                    "oid":"145243302943743250",
                                    "os":1,
                                    "otd":611,
                                    "ot":"X",
                                    "ov":130000,
                                    "onb":"平局",
                                    "on":"平局",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":""
                                }]
                            }
                        ],
                        "hpn":"15分钟进球(15:00-29:59)-独赢",
                        "mid":"2782347",
                        "hmm":0,
                        "hshow":"Yes",
                        "hpnb":"15分钟进球(15:00-29:59)-独赢",
                        "hSpecial":"2",
                        "hpt":1,
                        "hsw":"1,4,5",
                        "hpid":"32",
                        "hpon":123,
                        "mct":"76"
                    },
                    {
                        "hids":0,
                        "hl":[
                            {
                                "hid":"141512676753471502",
                                "hs":2,
                                "hv":"0",
                                "hmt":1,
                                "hn":null,
                                "ad3":"0",
                                "ad5":"1,15",
                                "ol":[{
                                    "oid":"141443986503110505",
                                    "os":1,
                                    "otd":613,
                                    "ot":"1",
                                    "ov":198000,
                                    "onb":"0",
                                    "on":"0",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":"T1"
                                },{
                                    "oid":"141531561795425181",
                                    "os":1,
                                    "otd":614,
                                    "ot":"2",
                                    "ov":182000,
                                    "onb":"0",
                                    "on":"0",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":"T2"
                                }]
                            }
                        ],
                        "hpn":"15分钟进球(开场-14:59)-让球",
                        "mid":"2782347",
                        "hmm":1,
                        "hshow":"Yes",
                        "hpnb":"15分钟进球(开场-14:59)-让球",
                        "hSpecial":"1",
                        "hpt":2,
                        "hsw":"1,2,3,4,5,6",
                        "hpid":"33",
                        "hpon":124,
                        "mct":"0.0"
                    },
                    {
                        "hids":0,
                        "hl":[
                            {
                                "hid":"145802024130205928",
                                "hs":2,
                                "hv":"0",
                                "hmt":1,
                                "hn":null,
                                "ad3":"0",
                                "ad5":"16,30",
                                "ol":[{
                                    "oid":"140582678618462253",
                                    "os":1,
                                    "otd":613,
                                    "ot":"1",
                                    "ov":198000,
                                    "onb":"0",
                                    "on":"0",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":"T1"
                                },{
                                    "oid":"141401357244112326",
                                    "os":1,
                                    "otd":614,
                                    "ot":"2",
                                    "ov":182000,
                                    "onb":"0",
                                    "on":"0",
                                    "onbl":"",
                                    "cds":"AO",
                                    "ots":"T2"
                                }]
                            }
                        ],
                        "hpn":"15分钟进球(15:00-29:59)-让球",
                        "mid":"2782347",
                        "hmm":1,
                        "hshow":"Yes",
                        "hpnb":"15分钟进球(15:00-29:59)-让球",
                        "hSpecial":"2",
                        "hpt":2,
                        "hsw":"1,2,3,4,5,6",
                        "hpid":"33",
                        "hpon":124,
                        "mct":"0.0"
                    },
                    {
                        "hids":1,
                        "hl":[
                            {
                                "hid":"148223433540382704",
                                "hs":2,
                                "hv":"0.5",
                                "hmt":1,
                                "hn":null,
                                "ad3":"15",
                                "ad5":"",
                                "ol":[{
                                    "oid":"140638423247367260",
                                    "os":1,
                                    "otd":615,
                                    "ot":"Over",
                                    "ov":292000,
                                    "onb":"0.5",
                                    "on":"大 0.5",
                                    "onbl":"大 ",
                                    "cds":"AO",
                                    "ots":"T1"
                                },{
                                    "oid":"148449386529523100",
                                    "os":1,
                                    "otd":616,
                                    "ot":"Under",
                                    "ov":132000,
                                    "onb":"0.5",
                                    "on":"小 0.5",
                                    "onbl":"小 ",
                                    "cds":"AO",
                                    "ots":"T2"
                                }]
                            }
                        ],
                        "hpn":"15分钟进球(开场-14:59)-大小",
                        "mid":"2782347",
                        "hmm":1,
                        "hshow":"Yes",
                        "hpnb":"15分钟进球(开场-14:59)-大小",
                        "hSpecial":"1",
                        "hpt":5,
                        "hsw":"1,2,3,4,5,6",
                        "hpid":"34",
                        "hpon":126,
                        "mct":"76"
                    },
                    {
                        "hids":1,
                        "hl":[
                            {
                                "hid":"142415326549114333",
                                "hs":2,
                                "hv":"0.5",
                                "hmt":1,
                                "hn":null,
                                "ad3":"30",
                                "ad5":"",
                                "ol":[{
                                    "oid":"147350222803184523",
                                    "os":1,
                                    "otd":615,
                                    "ot":"Over",
                                    "ov":278000,
                                    "onb":"0.5",
                                    "on":"大 0.5",
                                    "onbl":"大 ",
                                    "cds":"AO",
                                    "ots":"T1"
                                },{
                                    "oid":"142270454252905059",
                                    "os":1,
                                    "otd":616,
                                    "ot":"Under",
                                    "ov":136000,
                                    "onb":"0.5",
                                    "on":"小 0.5",
                                    "onbl":"小 ",
                                    "cds":"AO",
                                    "ots":"T2"
                                }]
                            }
                        ],
                        "hpn":"15分钟进球(15:00-29:59)-大小",
                        "mid":"2782347",
                        "hmm":1,
                        "hshow":"Yes",
                        "hpnb":"15分钟进球(15:00-29:59)-大小",
                        "hSpecial":"2",
                        "hpt":5,
                        "hsw":"1,2,3,4,5,6",
                        "hpid":"34",
                        "hpon":126,
                        "mct":"76"
                    }
                ],
                "lurl":"group1/M00/00/4C/CgURtV9Dg_OAcmmuAAAKihNNXOU918.png",
                "mprmc":"PA",
                "cosOvertime":false,
                "mhn":"西汉姆联",
                "betAmount":"0.00",
                "cds":"BG",
                "frmhn":[
                    "X"
                ],
                "compose":true,
                "operationTournamentSort":197,
                "cos15Minutes":true,
                "mhs":0,
                "mlet":"45:00",
                "hps5Minutes":[
                    {
                        "mid":"2782347",
                        "chpid":"361",
                        "hpid":"361",
                        "hpon":225,
                        "hshow":"No",
                        "hpn":"5分钟时段进球",
                        "hpnb":"5分钟时段进球",
                        "hpt":3,
                        "hsw":"1,4,5",
                        "hmm":0,
                        "hids":0,
                        "hl":[{
                            "hid":"144787243454308314",
                            "hs":2,
                            "hv":null,
                            "hmt":1,
                            "hn":null,
                            "title":[
                                {
                                    "osn":"00:00-04:59",
                                    "otd":1154
                                },
                                {
                                    "osn":"05:00-09:59",
                                    "otd":1155
                                },
                                {
                                    "osn":"10:00-14:59",
                                    "otd":1156
                                },
                                {
                                    "osn":"15:00-19:59",
                                    "otd":1157
                                },
                                {
                                    "osn":"20:00-24:59",
                                    "otd":1158
                                },
                                {
                                    "osn":"25:00-29:59",
                                    "otd":1159
                                },
                                {
                                    "osn":"30:00-34:59",
                                    "otd":1160
                                },
                                {
                                    "osn":"35:00-39:59",
                                    "otd":1161
                                },
                                {
                                    "osn":"40:00-45:00",
                                    "otd":1162
                                },
                                {
                                    "osn":"下半场-49:59",
                                    "otd":1163
                                },
                                {
                                    "osn":"50:00-54:59",
                                    "otd":1164
                                },
                                {
                                    "osn":"55:00-59:59",
                                    "otd":1165
                                },
                                {
                                    "osn":"60:00-64:59",
                                    "otd":1166
                                },
                                {
                                    "osn":"65:00-69:59",
                                    "otd":1167
                                },
                                {
                                    "osn":"70:00-74:59",
                                    "otd":1168
                                },
                                {
                                    "osn":"75:00-79:59",
                                    "otd":1169
                                },
                                {
                                    "osn":"80:00-84:59",
                                    "otd":1170
                                },
                                {
                                    "osn":"85:00-90:00",
                                    "otd":1171
                                },
                                {
                                    "osn":"无进球(0-0)",
                                    "otd":1172
                                },
                                {
                                    "osn":"绝杀球(含上/下半场补时)",
                                    "otd":1173
                                }
                            ],
                            "ol":[{
                                "oid":"140147595430109574",
                                "os":1,
                                "otd":1154,
                                "ot":"1-5",
                                "ov":990000,
                                "on":"00:00-04:59",
                                "onb":"00:00-04:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"141327760500343424",
                                "os":1,
                                "otd":1155,
                                "ot":"6-10",
                                "ov":760000,
                                "on":"05:00-09:59",
                                "onb":"05:00-09:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"141459221819271508",
                                "os":1,
                                "otd":1156,
                                "ot":"11-15",
                                "ov":760000,
                                "on":"10:00-14:59",
                                "onb":"10:00-14:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"146854356330575202",
                                "os":1,
                                "otd":1157,
                                "ot":"16-20",
                                "ov":760000,
                                "on":"15:00-19:59",
                                "onb":"15:00-19:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"149524124240924475",
                                "os":1,
                                "otd":1158,
                                "ot":"21-25",
                                "ov":760000,
                                "on":"20:00-24:59",
                                "onb":"20:00-24:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"144368042213065417",
                                "os":1,
                                "otd":1159,
                                "ot":"26-30",
                                "ov":760000,
                                "on":"25:00-29:59",
                                "onb":"25:00-29:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"144035506384033111",
                                "os":1,
                                "otd":1160,
                                "ot":"31-35",
                                "ov":740000,
                                "on":"30:00-34:59",
                                "onb":"30:00-34:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"146241683053000031",
                                "os":1,
                                "otd":1161,
                                "ot":"36-40",
                                "ov":740000,
                                "on":"35:00-39:59",
                                "onb":"35:00-39:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"148557412853212075",
                                "os":1,
                                "otd":1162,
                                "ot":"41-45",
                                "ov":740000,
                                "on":"40:00-45:00",
                                "onb":"40:00-45:00",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"145544342932535950",
                                "os":1,
                                "otd":1163,
                                "ot":"46-50",
                                "ov":730000,
                                "on":"下半场-49:59",
                                "onb":"下半场-49:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"144444039740522490",
                                "os":1,
                                "otd":1164,
                                "ot":"51-55",
                                "ov":590000,
                                "on":"50:00-54:59",
                                "onb":"50:00-54:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"143724902103691356",
                                "os":1,
                                "otd":1165,
                                "ot":"56-60",
                                "ov":590000,
                                "on":"55:00-59:59",
                                "onb":"55:00-59:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"147751142502723993",
                                "os":1,
                                "otd":1166,
                                "ot":"61-65",
                                "ov":620000,
                                "on":"60:00-64:59",
                                "onb":"60:00-64:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"142034600034511833",
                                "os":1,
                                "otd":1167,
                                "ot":"66-70",
                                "ov":620000,
                                "on":"65:00-69:59",
                                "onb":"65:00-69:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"140931937214032035",
                                "os":1,
                                "otd":1168,
                                "ot":"71-75",
                                "ov":620000,
                                "on":"70:00-74:59",
                                "onb":"70:00-74:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"147220733710608513",
                                "os":1,
                                "otd":1169,
                                "ot":"76-80",
                                "ov":610000,
                                "on":"75:00-79:59",
                                "onb":"75:00-79:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"143059065549014445",
                                "os":1,
                                "otd":1170,
                                "ot":"81-85",
                                "ov":610000,
                                "on":"80:00-84:59",
                                "onb":"80:00-84:59",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"145501131640843357",
                                "os":1,
                                "otd":1171,
                                "ot":"86-90",
                                "ov":610000,
                                "on":"85:00-90:00",
                                "onb":"85:00-90:00",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"147322604114381120",
                                "os":1,
                                "otd":1172,
                                "ot":"NoGoal",
                                "ov":1150000,
                                "on":"无进球(0-0)",
                                "onb":"无进球(0-0)",
                                "cds":"AO",
                                "ots":""
                            },{
                                "oid":"145143313068154123",
                                "os":1,
                                "otd":1173,
                                "ot":"ClutchGoal",
                                "ov":530000,
                                "on":"绝杀球(含上/下半场补时)",
                                "onb":"绝杀球(含上/下半场补时)",
                                "cds":"AO",
                                "ots":""
                            }]
                        }]
                    },
                    {
                        "mid":"2768850",
                        "chpid":"362",
                        "hpid":"362",
                        "hpon":226,
                        "hshow":"No",
                        "hpn":"第 {!goalnr} 个进球时分(5min)",
                        "hpnb":"第 {!goalnr} 个进球时分(5min)",
                        "hpt":3,
                        "hsw":"1,4,5",
                        "hmm":0,
                        "hids":0,
                        "hl":[{}]
                    }
                ],
                "cosPenalty":false,
                "hpsCorner":[],
                "mhid":"111081",
                "hpsPunish":[],
                "mrmc":"",
                "mid":"2782347",
                "mess":1,
                "cosBold":true,
                "lss":null,
                "mmp":"0",
                "mststi":"0",
                "mms":-1,
                "mbmty":1,
                "regionIdSort":1,
                "mhlu":[
                    "group1/M00/17/25/CgURtmMm5nyAVPt0AAAPeEdf3HE346.png"
                ],
                "seid":"122244",
                "mstst":"0",
                "malut":"",
                "man":"阿森纳",
                "frman":[
                    "A"
                ],
                "mat":"",
                "mng":0,
                "mststr":"0",
                "hps":[
                    {
                        "mid":"2782347",
                        "chpid":"4",
                        "hpid":"4",
                        "hpon":4,
                        "hshow":"Yes",
                        "hpn":"全场让球",
                        "hpnb":"全场让球",
                        "hpt":2,
                        "hsw":"1,2,3,4,5,6",
                        "hmm":1,
                        "hids":1,
                        "hl":[{
                            "hid":"146152337505451804",
                            "hs":2,
                            "hv":"0",
                            "hmt":1,
                            "hn":1,
                            "ol":[{
                                "oid":"143373208291248615",
                                "os":1,
                                "otd":3,
                                "ot":"1",
                                "ov":202000,
                                "on":"0",
                                "onb":"0",
                                "cds":"AO",
                                "ots":"T1"
                            },{
                                "oid":"146546415241642409",
                                "os":1,
                                "otd":4,
                                "ot":"2",
                                "ov":180000,
                                "on":"0",
                                "onb":"0",
                                "cds":"AO",
                                "ots":"T2"
                            }]
                        }]
                    }
                ],
                "hpsCompose":[],
                "mvs":-1,
                "hpsPenalty":[],
                "mststs":0,
                "mearlys":0,
                "tf":false,
                "th":0,
                "cosPromotion":false,
                "mfo":null,
                "mft":0,
                "tn":"英格兰联赛杯",
                "msc":[],
                "hpsPromotion":[],
                "hpsOutright":[]
            }
        ],
        "msg":"成功",
        "ts":1698388920348
    }
    if(res && res.code == 200){
        slidEeventList.value = res.data?.map((item)=>{
            return {
                isGame:true,
                anchorName:"名称1",//主播名称
                anchorAvatar:"https://cdn.quasar.dev/img/quasar.jpg",//主播头像
                gameName:item.tn,//比赛名称
                gameParticipants:[//参赛方信息
                    {
                        name:item.mhn,
                        imgFile:item.mhlu,
                        initials:item.frmhn,
                        csid:item.csid
                    },
                    {
                        name:item.man,
                        imgFile:item.malu,
                        initials:item.frman,
                        csid:item.csid
                    }
                ],
                mid:item.mid,
                csid:item.csid
            }
        })
    }
}

getSwiperImgList();
getSwiperList();

</script>
<style scoped lang="scss">
    .swiper-wap{
        width: 100%;
        padding: 0 0.1rem;
        height: 0.52rem;
        display: flex;
        margin: 0.04rem 0;
        .swiper-content{
            height: 100%;
            &.swiper-left{
                width: 1.4rem;
                margin-right: 0.08rem;
                border-radius: 0.08rem;
                overflow: hidden;
            }
            &.swiper-right{
                flex: 1;
                border-radius: 0.08rem;
                overflow: hidden;
            }
        }
    }
</style>