export const responseData = {
  code: '0000000',
  data: {
    ascs: null,
    betTotalAmount: '300.00',
    current: '1',
    descs: null,
    hasNext: false,
    hasPrevious: false,
    optimizeCountSql: true,
    pages: '1',
    preBetTotalAmount: '0.00',
    profit: '0.00',
    record: null,
    records: [
      {
        acCode: '',
        addition: 0,
        backAmount: null,
        betTime: '1687761719204',
        betTimeStr: '2023-06-26',
        enablePreSettle: false,
        initPresettleWs: false,
        langCode: 'zh',
        managerCode: 4,
        marketType: 'EU',
        maxCashout: null,
        maxWinAmount: 35.0,
        orderAmountTotal: 100.0,
        orderNo: '5063285157627335',
        orderStatus: '0',
        orderVOS: [
          {
            batchNo: '',
            beginTime: '1687759200000',
            betResult: 0,
            betStatus: 0,
            cancelType: 0,
            closingTime: null,
            hs: 2,
            langCode: '',
            marketId: '78265217508837076',
            marketType: 'EU',
            marketValue: 'TES Challenger',
            matchDay: '',
            matchId: '78265101094576270',
            matchInfo: 'Bilibili Gaming Junior v TES Challenger',
            matchName: 'LDL 2023 Oddin测试联赛',
            matchType: 2,
            oddFinally: '1.350',
            oddsValue: '',
            outrightYear: '',
            playId: 30006,
            playName: '第2局单局获胜',
            playOptions: 'T2',
            playOptionsId: '78265217508994830',
            scoreBenchmark: '',
            settleScore: '',
            sportId: 100,
            sportName: '英雄联盟',
            tournamentId: '72413510859293786',
            tournamentPic: ''
          }
        ],
        outcome: null,
        preBetAmount: null,
        preOrder: null,
        preSettleBetAmount: null,
        profitAmount: null,
        seriesSum: 1,
        seriesType: '1',
        seriesValue: '单关',
        settleTime: null,
        settleType: 1
      },
      {
        acCode: '',
        addition: 0,
        backAmount: null,
        betTime: '1687761650000',
        betTimeStr: '2023-06-26',
        enablePreSettle: false,
        initPresettleWs: true,
        langCode: 'zh',
        managerCode: 1,
        marketType: 'EU',
        maxCashout: null,
        maxWinAmount: 102.0,
        orderAmountTotal: 100.0,
        orderNo: '5063284950003333',
        orderStatus: '0',
        orderVOS: [
          {
            batchNo: '',
            beginTime: '1687755000000',
            betResult: 0,
            betStatus: 0,
            cancelType: 0,
            closingTime: null,
            hs: 2,
            langCode: '',
            marketId: '148263808572239128',
            marketType: 'EU',
            marketValue: '小 3.5/4',
            matchDay: '',
            matchId: '3488601',
            matchInfo: 'adela-钦兰 v adela-乌克兰(0-0)',
            matchName: '格鲁吉亚乙级联赛',
            matchType: 2,
            oddFinally: '2.02',
            oddsValue: '',
            outrightYear: '',
            playId: 2,
            playName: '全场大小',
            playOptions: 'Under',
            playOptionsId: '142196242133923973',
            scoreBenchmark: '',
            settleScore: '',
            sportId: 1,
            sportName: '足球',
            tournamentId: '1184098',
            tournamentPic: ''
          }
        ],
        outcome: null,
        preBetAmount: null,
        preOrder: null,
        preSettleBetAmount: null,
        profitAmount: null,
        seriesSum: 1,
        seriesType: '1',
        seriesValue: '单关',
        settleTime: null,
        settleType: 1
      },
      {
        acCode: '',
        addition: 0,
        backAmount: null,
        betTime: '1687761615825',
        betTimeStr: '2023-06-26',
        enablePreSettle: false,
        initPresettleWs: true,
        langCode: 'zh',
        managerCode: 1,
        marketType: 'EU',
        maxCashout: null,
        maxWinAmount: 109.0,
        orderAmountTotal: 100.0,
        orderNo: '5063284847478332',
        orderStatus: '0',
        orderVOS: [
          {
            batchNo: '',
            beginTime: '1687755000000',
            betResult: 0,
            betStatus: 0,
            cancelType: 0,
            closingTime: null,
            hs: 2,
            langCode: '',
            marketId: '149965493087142153',
            marketType: 'EU',
            marketValue: '大 4',
            matchDay: '',
            matchId: '3488601',
            matchInfo: 'adela-钦兰 v adela-乌克兰(0-0)',
            matchName: '格鲁吉亚乙级联赛',
            matchType: 2,
            oddFinally: '2.09',
            oddsValue: '',
            outrightYear: '',
            playId: 2,
            playName: '全场大小',
            playOptions: 'Over',
            playOptionsId: '145459531702521347',
            scoreBenchmark: '',
            settleScore: '',
            sportId: 1,
            sportName: '足球',
            tournamentId: '1184098',
            tournamentPic: ''
          }
        ],
        outcome: null,
        preBetAmount: null,
        preOrder: null,
        preSettleBetAmount: null,
        profitAmount: null,
        seriesSum: 1,
        seriesType: '1',
        seriesValue: '单关',
        settleTime: null,
        settleType: 1
      }
    ],
    searchCount: true,
    size: '50',
    total: '3'
  },
  msg: '成功',
  ts: 1688908814072
}
export const frt = () => {
  console.log(1111111111111111)
}
