

const  config ={
    
        "--qq--activity-bg-color":" #fff",
        "--qq--activity-bg-color-4":" #e7eaee",
        "--qq--activity-bg-color-5":" #fcfcfc",
        "--qq--activity-bg-color-6":" #ff0602",
        "--qq--activity-bg-color-8":" #6b2200",
        "--qq--activity-bg-color-9":" lightyellow",
        "--qq--activity-bg-color-10":" #d8d8d8",
        "--qq--activity-bg-color-11":" rgba(0, 0, 0, 0.9)",
        "--qq--activity-bg-color-12":" rgba(255, 255, 255, 0.8)",
        "--qq--activity-bg-color-13":" #fff",
        "--qq--activity-bg-color-14":" #a9a9a9",
        "--qq--activity-bg-color-15":" #ff4040",
        "--qq--activity-text-color":" #5e637e",
        "--qq--activity-text-color-2":" #333333",
        "--qq--activity-text-color-3":" #666",
        "--qq--activity-text-color-5":" #999",
        "--qq--activity-text-color-6":" #e7eaee",
        "--qq--activity-text-color-7":" #ff0602",
        "--qq--activity-text-color-8":" #fee4b5",
        "--qq--activity-text-color-9":" #fffcf4",
        "--qq--activity-text-color-10":" #3a3a3a",
        "--qq--activity-text-color-11":" #565656",
        "--qq--activity-text-color-12":" #000",
        "--qq--activity-text-color-13":" #de6f04",
        "--qq--activity-text-color-14":" #171616",
        "--qq--activity-text-color-15":" #ff8b00",
        "--qq--activity-text-color-blue":" #007dff",
        "--qq--activity-text-color-gray":" #5e637e",
        "--qq--activity-text-color-red":" #e93333",
        "--qq--activity-text-color-active":" #fff",
        "--qq--activity-bd-color":" #fff",
        "--qq--activity-bd-color-5":" #e4e4e4",
        "--qq--activity-bd-color-6":" #d2d2d2",
        "--qq--activity-bd-color-7":" #999",
        "--qq--activity-bd-color-9":" #d9d9d9",
        "--qq--activity-bd-img-gradient":" linear-gradient(180deg, #ffffff 0%, #f3f3f3 77%, #fafdff 100%)",
        "--qq--activity-bd-img-gradient-4":" radial-gradient(at 50% 40%, #fff 2px, #a9a9a9 80%)",
        "--qq--activity-bd-img-gradient-5":" radial-gradient(at 50% 40%, #fff 2px, #ff4040 80%)",
        "--qq--activity-bd-img-gradient-6":" radial-gradient(at 50% 40%, #fff 2px, deepskyblue 80%)",
        "--qq--activity-bd-img-gradient-7":" radial-gradient(at 50% 40%, #fff 2px, yellow 80%)",
        "--qq--activity-bd-img-gradient-8":" linear-gradient(-88deg, #ffffff 0%, #f7f8f9 50%, #ffffff 100%)",
        "--qq--activity-bd-img-gradient-9":" linear-gradient(268deg, #b05500 0%, #f8c90d 31%, #fff8de 50%, #f8c600 80%, #aa4b00 100%)",
        "--qq--activity-box-shadow":" 0 1px 8px 0 rgba(0, 0, 0, 0.1)",
        "--qq--activity-box-shadow-2":" 0 2px 40px 0 rgba(0, 0, 0, 0.1)",
        "--qq--activity-box-shadow-3":" lightyellow",
        "--qq--activity-box-shadow-4":" rgba(0, 0, 0, 0.3)",
        "--qq--activity-box-shadow-5":" inset 0px 1px 8px 0px rgba(189, 72, 72, 0.5), 0px 2px 4px 0px rgba(0, 0, 0, 0.27), 0px 2px 7px 0px rgba(0, 0, 0, 0.26), 0px 2px 14px 0px rgba(0, 0, 0, 0.05)",
        "--qq--activity-text-shadow":" 0 2px 4px #e50000, 0 -2px 3px #f0ff04",
        "--qq--activity-text-shadow-2":" 0 2px 4px rgba(0, 0, 0, 0.5)",
        "--qq--activity-drop-shadow":" #ff4040",
        "--qq--activity-drop-shadow-2":" deepskyblue",
        "--qq--activity-drop-shadow-3":" yellow",
        "--qq--activity-text-color-4":" #179CFF",
        "--qq--activity-text-color-16":" #ffffff",
        "--qq--activity-bd-color-2":" #A4BEFE",
        "--qq--activity-bd-color-3":" transparent",
        "--qq--activity-bd-color-4":" #ddd",
        "--qq--activity-bg-color-2":" #F0F6FF",
        "--qq--activity-bg-color-3":" #c3d5f5",
        "--qq--activity-bg-color-7":" #179CFF",
        "--qq--activity-bd-img-gradient-2":" linear-gradient(180deg, #FFFFFF 22%, #F7F8FF 100%)",
        "--qq--activity-bd-img-gradient-3":" linear-gradient(180deg, #62B6FF 0%, #3D72FA 100%)",
        "--qq--activity-tab-bg-img-active":" linear-gradient(180deg, #62B6FF 0%, #3D72FA 100%)",
        "--qq--activity-btn-bg-img1":" url(public/yazhou-pc/image/activity_imgs/imgs/get_box_y0.svg)",
        "--qq--activity-btn-bg-img2":" url(public/yazhou-pc/image/activity_imgs/imgs/get_bonus_y0.svg)",
        "--qq--activity-bd-img-1":" url(public/yazhou-pc/image/activity_imgs/imgs/title_bg_y0.svg)",
        "--qq--activity-bd-img-2":" url(public/yazhou-pc/image/activity_imgs/imgs/text-pre_y0.svg)",
        "--qq--activity-bd-img-3":" url(public/yazhou-pc/image/activity_imgs/imgs/game_record.png)",
        "--qq--activity-bd-img-4":" url(public/yazhou-pc/image/activity_imgs/imgs/get_all_bonus_y0.svg)",
        "--qq--activity-bd-img-5":" url(public/yazhou-pc/image/activity_imgs/imgs/waiting_y0.svg)",
        "--qq--activity-bd-img-6":" url(public/yazhou-pc/image/activity_imgs/imgs/game_record.png)",
        
}