export const test_data = [
    {
        "eventCode": "dang_poss",
        "eventName": "危险球位置",
        "eventEnName": "Danger possession",
        "eventType": 2,
        "sourceType": 1,
        "sportId": 1,
        "homeAway": "away",
        "currentTime": 1485,
        "score": "1:0",
        "setScore": "0:0",
        "currentScore": "null:null",
        "dataSourceCode": "RB",
        "eventTime": 1701833462955,
        "t1": 1,
        "t2": 0,
        "canceled": 0,
        "extraInfo": "",
        "remark": null,
        "matchPeriodId": 6,
        "createTime": 1701833462983
    },
    {
        "eventCode": "dangerous_attack",
        "eventName": "危险进攻",
        "eventEnName": "Dangerous attack",
        "eventType": 2,
        "sourceType": 1,
        "sportId": 1,
        "homeAway": "away",
        "currentTime": 1575,
        "score": "1:0",
        "setScore": "0:0",
        "currentScore": "null:null",
        "dataSourceCode": "RB",
        "eventTime": 1701833553234,
        "t1": 14,
        "t2": 6,
        "canceled": 0,
        "extraInfo": "",
        "remark": null,
        "matchPeriodId": 6,
        "createTime": 1701833553383
    },
    {
        "eventCode": "ball_safe",
        "eventName": "己方半场控球",
        "eventEnName": "Safe ball",
        "eventType": 1,
        "sourceType": 1,
        "sportId": 1,
        "homeAway": "away",
        "currentTime": 1570,
        "score": "1:0",
        "setScore": "0:0",
        "currentScore": "null:null",
        "dataSourceCode": "RB",
        "eventTime": 1701833548102,
        "t1": 1,
        "t2": 0,
        "canceled": 0,
        "extraInfo": "",
        "remark": null,
        "matchPeriodId": 6,
        "createTime": 1701833548302
    },
    {
        "eventCode": "goal",
        "eventName": "进球",
        "eventEnName": "Goal",
        "eventType": 4,
        "sourceType": 1,
        "sportId": 1,
        "homeAway": "home",
        "currentTime": 247,
        "score": "1:0",
        "setScore": "0:0",
        "currentScore": "null:null",
        "dataSourceCode": "RB",
        "eventTime": 1701832225272,
        "t1": 1,
        "t2": 0,
        "canceled": 0,
        "extraInfo": "-1",
        "remark": null,
        "matchPeriodId": 6,
        "createTime": 1701832225330
    },
    {
        "eventCode": "goal_confirm",
        "eventName": "进球确认",
        "eventEnName": "Goal confirmed",
        "eventType": 1,
        "sourceType": 1,
        "sportId": 1,
        "homeAway": "home",
        "currentTime": 333,
        "score": "1:0",
        "setScore": "0:0",
        "currentScore": "null:null",
        "dataSourceCode": "RB",
        "eventTime": 1701832310780,
        "t1": 1,
        "t2": 0,
        "canceled": 0,
        "extraInfo": "",
        "remark": null,
        "matchPeriodId": 6,
        "createTime": 1701832310818
    },
]